//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Management.Presentation.Mvc.WcfServiceLayer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceLayer.ISchedulerReadFacadeService")]
    public interface ISchedulerReadFacadeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchedulerReadFacadeService/ReadOverviewData", ReplyAction="http://tempuri.org/ISchedulerReadFacadeService/ReadOverviewDataResponse")]
        Quartz.Management.Dto.Model.OverviewDataDto ReadOverviewData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchedulerReadFacadeService/ReadJobDetail", ReplyAction="http://tempuri.org/ISchedulerReadFacadeService/ReadJobDetailResponse")]
        Quartz.Management.Dto.Model.JobDetailDto ReadJobDetail(string name, string group);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchedulerReadFacadeServiceChannel : Quartz.Management.Presentation.Mvc.WcfServiceLayer.ISchedulerReadFacadeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchedulerReadFacadeServiceClient : System.ServiceModel.ClientBase<Quartz.Management.Presentation.Mvc.WcfServiceLayer.ISchedulerReadFacadeService>, Quartz.Management.Presentation.Mvc.WcfServiceLayer.ISchedulerReadFacadeService {
        
        public SchedulerReadFacadeServiceClient() {
        }
        
        public SchedulerReadFacadeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchedulerReadFacadeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerReadFacadeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerReadFacadeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Quartz.Management.Dto.Model.OverviewDataDto ReadOverviewData() {
            return base.Channel.ReadOverviewData();
        }
        
        public Quartz.Management.Dto.Model.JobDetailDto ReadJobDetail(string name, string group) {
            return base.Channel.ReadJobDetail(name, group);
        }
    }
}
